### ISSUE TITLE
null

### ISSUE THREAD

**Issue by SirCipher** [AmrikSadhra/OpenNFS#1]
`Snake snake = new Snake();`

**Comment by AmrikSadhra** [comment]
Attempting to repro but hitting 'no appropriate default constructor available'. Possible that your own snakeage has transcended this realm and is gradually infecting your notepad.exe. Recommend 'git reset --hard y0ur-l1f3'.

**Comment by SirCipher** [comment]
Did you ever fix this?

**Comment by SirCipher** [comment]
Just wondering, what beans do you use for this project?
